import { agentsConfig } from './agents.config';
import { KNOWLEDGE_SEED, type KnowledgeSeed } from './knowledge.seed';
import { buildSystemPromptTemplate } from './prompts';
import type { AgentConfig } from './schemas';

/** SPEC section 14: default monthly budget per agent is 2 million input tokens. */
export const DEFAULT_MONTHLY_TOKEN_BUDGET = 2_000_000;

export interface SeedMember {
  email: string;
  role: 'owner' | 'staff' | 'viewer';
}

/** Local development accounts (magic link mail lands in the local Mailpit inbox). */
export const DEV_MEMBERS: readonly SeedMember[] = [
  { email: 'owner@intelligo.test', role: 'owner' },
  { email: 'staff@intelligo.test', role: 'staff' },
  { email: 'viewer@intelligo.test', role: 'viewer' },
];

export interface SeedOptions {
  orgId: string;
  modelWork: string;
  monthlyTokenBudget?: number;
  agents?: readonly AgentConfig[];
  members?: readonly SeedMember[];
  knowledge?: readonly KnowledgeSeed[];
}

const sqlString = (value: string): string => `'${value.replaceAll("'", "''")}'`;

const sqlTextArray = (values: readonly string[]): string =>
  values.length === 0 ? `'{}'::text[]` : `array[${values.map(sqlString).join(', ')}]::text[]`;

const sqlJson = (value: unknown): string => `${sqlString(JSON.stringify(value))}::jsonb`;

/** Builds supabase/seed.sql from agents.config.ts. Output is deterministic for snapshot checks. */
export function generateSeedSql(options: SeedOptions): string {
  const agents = options.agents ?? agentsConfig;
  const budget = options.monthlyTokenBudget ?? DEFAULT_MONTHLY_TOKEN_BUDGET;
  const org = `${sqlString(options.orgId)}::uuid`;

  const agentValues = agents
    .map((agent) =>
      [
        sqlString(agent.id),
        org,
        sqlString(agent.name),
        sqlString(agent.role),
        sqlString(agent.focus),
        sqlString(buildSystemPromptTemplate(agent)),
        sqlString(options.modelWork),
        sqlTextArray(agent.tools),
        sqlString(agent.deskId),
        sqlJson(agent.appearance),
        sqlTextArray(agent.idleLines),
        agent.isManager ? 'true' : 'false',
        'true',
        String(budget),
      ].join(',\n    '),
    )
    .map((row) => `  (\n    ${row}\n  )`)
    .join(',\n');

  const members = options.members ?? DEV_MEMBERS;
  const knowledge = options.knowledge ?? KNOWLEDGE_SEED;
  const knowledgeValues = knowledge
    .map(
      (doc) =>
        `  (${sqlString(doc.id)}::uuid, ${org}, ${sqlString(doc.title)}, ${sqlString(doc.content)}, ${sqlTextArray(doc.tags)})`,
    )
    .join(',\n');
  const memberValues = members
    .map((m) => `  (${org}, ${sqlString(m.email.toLowerCase())}, ${sqlString(m.role)})`)
    .join(',\n');

  const stateValues = agents
    .map(
      (agent) =>
        `  (${sqlString(agent.id)}, ${org}, 'working', ${sqlString(agent.idleLines[0] ?? '')}, null, 'desk')`,
    )
    .join(',\n');

  return `-- Generated by packages/shared/scripts/generate-seed.ts from agents.config.ts.
-- Do not edit by hand. Run \`pnpm db:seed:gen\` after changing the agent config.

insert into public.settings (org_id, auto_approve_kinds, dry_run, usd_to_idr)
values (${org}, '{}'::text[], true, 16000)
on conflict (org_id) do nothing;

insert into public.agents (
  id, org_id, name, role, focus, system_prompt, model, tools, desk_id,
  appearance, idle_lines, is_manager, enabled, monthly_token_budget
)
values
${agentValues}
on conflict (id) do update set
  name = excluded.name,
  role = excluded.role,
  focus = excluded.focus,
  tools = excluded.tools,
  desk_id = excluded.desk_id,
  appearance = excluded.appearance,
  idle_lines = excluded.idle_lines,
  is_manager = excluded.is_manager;

insert into public.agent_states (agent_id, org_id, activity, status_text, current_task_id, target_spot)
values
${stateValues}
on conflict (agent_id) do nothing;
${
  members.length > 0
    ? `
insert into public.org_members (org_id, email, role)
values
${memberValues}
on conflict (email) do nothing;
`
    : ''
}${
    knowledge.length > 0
      ? `
insert into public.knowledge_docs (id, org_id, title, content, tags)
values
${knowledgeValues}
on conflict (id) do nothing;
`
      : ''
  }`;
}
